python client.py 0 localhost 8000 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_0.txt &
python client.py 1 localhost 8001 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_1.txt &
python client.py 2 localhost 8002 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_2.txt &
python client.py 3 localhost 8003 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_3.txt &
python client.py 4 localhost 8004 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_4.txt &
python client.py 5 localhost 8005 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_5.txt &
python client.py 6 localhost 8006 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_6.txt &
python client.py 7 localhost 8007 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_7.txt &
python client.py 8 localhost 8008 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_8.txt &
python client.py 9 localhost 8009 replica_config.json 5 < /Users/taosixu/Desktop/EECS591/P1/msg/messages_9.txt &
